/*******************************************************************************
* Problem 2 : Even Fibonacci Numbers                                           *
*                                                                              *
* Each new term in the Fibonacci sequence is generated by adding the previous  *
* two terms. By starting with 1 and 2, the first 10 terms will be:             *
*                                                                              *
*          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                              *
*                                                                              *
* By considering the terms in the Fibonacci sequence whose values do not       *
* exceed four million, find the sum of the even-valued terms.                  *
*******************************************************************************/

#include <iostream>
#include <chrono>
#include <cstdlib>
#include <vector>

int main (int argc, char *argv[])
{
    /* Input processing */
    if (argc != 1)
    {
        std::cout << "Usage : ./002_even_fibonacci_numbers" << std::endl;
        return -1;
    }

    // écrire la fonction (calculer la suite de fibonnaci) de manière itérative
    // Si on veut le stocker le minimum de valeurs :
    // Stocker dans un tableau les 3 derniers nombres de fibonacci
    // Sotcker la somme (incrémenter les nombres pairs au fur et à mesure)

    return 0;
}